// SleepLamp · types.h — shared data model + global declarations
#pragma once
#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "ShubhSensor.h"
#include "config.h"

// All telemetry: C1001 (radar) + DHT11
struct SensorData {
  bool valid = false; uint32_t seq = 0;
  // live human (radar)
  int presence=0, motion=0, movingRange=0, distance=0;
  int heartRate=0, breathRate=0, breathState=4;
  // live sleep (radar)
  int inBed=0, sleepState=3, wakeDur=0, lightDur=0, deepDur=0, quality=0;
  int disturbance=3, rating=0, abnormal=0;
  // composite (radar)
  int cResp=0, cHeart=0, cTurn=0, cLarge=0, cMinor=0, cApnea=0;
  // nightly statistics (radar)
  int sScore=0, sSleepTime=0, sWake=0, sShallow=0, sDeep=0,
      sOOB=0, sExit=0, sTurn=0, sResp=0, sHeart=0, sApnea=0;
  // environment (DHT11)
  int  tempC=0, humidity=0;
  bool envValid=false;
};

// Lamp light state
struct LightState {
  int mode   = 0;        // 0 auto, 1 manual, 2 off
  int r = 255, g = 150, b = 60;
  int bright = 60;       // 0..100 %
};

// Smart alarm
struct AlarmState {
  bool enabled = false;
  int  hour = 7, minute = 0;
  int  window = ALARM_WINDOW_MIN;
  bool firing = false;
};

// On-device sleep-session recording (1 sample/min, ~10 h ring buffer).
// Survives page refreshes — the hypnogram is rebuilt from this, not browser RAM.
#define SESS_MAX 600
struct SessSample { uint8_t stage, hr, br; };

// Live output of the on-device sleep-staging engine (Sleep.ino).
// stage: 0 deep, 1 light, 2 awake-in-bed, 3 no session — same coding as radar.
struct SleepLive {
  bool active = false;
  int  stage = 3;
  int  bedMin=0, sleepMin=0, deepMin=0, lightMin=0, awakeMin=0;
  int  onsetMin=-1, wakes=0, turns=0, score=0;   // score = live estimate
  char since[6] = "--:--";                       // session start clock
};

// A finished session, as saved to history. Generated by the engine at session
// end (out of bed > OOB_END_EP min) or via the dashboard "End session" button.
struct NightReport {
  bool valid = false;
  char when[20] = "";                            // "YYYY-MM-DD HH:MM"
  int  bedMin=0, sleepMin=0, deepMin=0, lightMin=0, awakeMin=0;
  int  onsetMin=0, wakes=0, turns=0, avgHR=0, avgBR=0, apnea=0, score=0;
};

// ---- globals (defined in sleeplamp.ino) ----
extern SensorData              g;
extern LightState              light;
extern AlarmState              alarmCfg;
extern WebServer               server;
extern ShubhSensor             hu;
extern SemaphoreHandle_t       mux;
extern char                    timeStr[6];   // "HH:MM"
extern bool                    timeOk;
extern volatile bool           g_sensorReset; // web -> sensor task: please reset the radar
extern volatile bool           radarOk;       // sensor task -> world: radar link healthy
extern volatile bool           g_endSession;  // web -> engine: end session, build report
extern volatile bool           g_alarmStop;   // touch/web -> alarm: stop firing now
extern volatile bool           g_lightDirty;  // Matter -> loop: a hub command changed the lamp, re-apply
extern SleepLive               live;          // engine -> world (guarded by mux)
extern NightReport             lastReport;    // most recent saved session (guarded by mux)
extern SessSample              sessBuf[SESS_MAX];
extern int                     sessN, sessStart;

// ---- entry points across the .ino tabs ----
void   sensorTask(void*);     // Sensor.ino
void   envTask(void*);        // Env.ino
void   lightBegin();          // Light.ino
void   lightApply();          // Light.ino
void   lightAuto();           // Light.ino
void   lightSunrise(float p); // Light.ino
void   lightBootTest();       // Light.ino
void   timeBegin();           // Alarm.ino
bool   alarmCheck();          // Alarm.ino
void   touchBegin();          // Touch.ino  (TTP223 init)
void   handleTouch();         // Touch.ino  (poll + act, called every loop)
void   matterBegin();         // Matter.ino (start Matter once WiFi is up)
void   matterLoop();          // Matter.ino (pairing-status prints, called every loop)
void   matterReflect(int r, int g, int b);  // Matter.ino (push lamp state -> hub)
void   storeBegin();          // Store.ino
void   reportSave(NightReport& r);  // Store.ino — stamp + append to history
void   reportLoadLast();      // Store.ino — restore last report at boot
void   sleepFeed(const SensorData& s, SleepLive& outLive,
                 NightReport& outRep, bool& repReady);  // Sleep.ino
void   handleData();          // Api.ino    (live JSON snapshot)
void   handleSession();       // Api.ino    (tonight's stage timeline)
void   handleLight();         // Control.ino
void   handleAlarm();         // Control.ino
void   handleReport();        // Control.ino (/api/report?end=1 -> end session now)
void   handleSensor();        // Control.ino (radar recalibrate)
void   handleHistory();       // Store.ino
void   handleExport();        // Store.ino  (download history.csv)
void   handleRoot();          // WebUI.ino  (dashboard page)
void   handleManifest();      // WebUI.ino  (PWA)
void   settingsBegin();       // Settings.ino (load light+alarm from NVS)
void   settingsSaveLight();   // Settings.ino
void   settingsSaveAlarm();   // Settings.ino
// Provision.ino — WiFi portal, OTA, factory reset
String getWifiSsid();  String getWifiPass();
void   handleWifiPage();      void handleWifiSave();
void   handleUpdatePage();    void handleUpdateDone();  void handleUpdateUpload();
void   handleFactoryReset();
